from enum import Enum
from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class UnifiedEmotion(str, Enum):
    """Standardized emotion taxonomy mapped across both acoustic and semantic models."""

    NEUTRAL = "NEUTRAL"
    HAPPY = "HAPPY"
    SAD = "SAD"
    ANGRY = "ANGRY"
    FEARFUL = "FEARFUL"
    DISGUST = "DISGUST"
    SURPRISED = "SURPRISED"
    AMBIGUOUS = "AMBIGUOUS"


class EmotionPrediction(BaseModel):
    """A single scored emotion prediction from text or acoustic models."""

    label: UnifiedEmotion = Field(..., description="The standardized emotion category.")
    original_label: str = Field(
        ..., description="The raw label output directly by the underlying model."
    )
    score: float = Field(
        ..., ge=0.0, le=1.0, description="Confidence score bounded between 0.0 and 1.0."
    )


class TimelineEvent(BaseModel):
    """A single speaker turn synchronized with transcript text and emotional classification."""

    segment_id: int = Field(..., description="Sequential index of the segment.")
    speaker: str = Field(..., description="Diarized speaker tag (e.g., 'SPEAKER_00').")
    start_time: float = Field(..., ge=0.0, description="Start timestamp in seconds.")
    end_time: float = Field(..., ge=0.0, description="End timestamp in seconds.")
    text: str = Field(..., description="The spoken text for this turn.")
    semantic_emotion: List[EmotionPrediction] = Field(
        default_factory=list,
        description="Ranked emotion predictions derived from the transcript text.",
    )
    acoustic_emotion: List[EmotionPrediction] = Field(
        default_factory=list,
        description="Ranked emotion predictions derived from the raw audio waveform.",
    )
    is_conflict: bool = Field(
        default=False,
        description="Flag indicating semantic vs acoustic valence contradiction (e.g., sarcasm, masking).",
    )
    is_ambiguous: bool = Field(
        default=False,
        description="Flag indicating mixed or borderline emotional distribution (low confidence margin).",
    )
    conflict_detail: Optional[str] = Field(
        default=None, description="Explanation of the emotional conflict or ambiguity if detected."
    )
    is_interruption: bool = Field(
        default=False,
        description="Flag indicating this turn interrupted or talked over another speaker.",
    )
    interrupted_by: Optional[str] = Field(
        default=None, description="Speaker ID of who interrupted this turn, if cross-talk occurred."
    )
    overlap_duration: float = Field(
        default=0.0,
        ge=0.0,
        description="Duration in seconds of overlapping speech during this turn.",
    )


class AgentSynthesis(BaseModel):
    """Structured analytical conclusions generated by the downstream LangGraph agent."""

    summary: str = Field(..., description="Overview of conversational dynamics and progression.")
    escalation_detected: bool = Field(
        ..., description="Flag indicating presence of hostility or tension."
    )
    primary_speaker_sentiments: Dict[str, str] = Field(
        ..., description="Dominant sentiment or behavioral trajectory per detected speaker."
    )
    flagged_anomalies: List[str] = Field(
        default_factory=list,
        description="Noted text-versus-tone discrepancies (e.g., sarcasm, masking).",
    )
    interruption_count: int = Field(
        default=0,
        ge=0,
        description="Total number of speech interruption / talk-over events detected.",
    )
    total_overtalk_seconds: float = Field(
        default=0.0, ge=0.0, description="Total seconds of overlapping multi-speaker speech."
    )
    overtalk_ratio: float = Field(
        default=0.0,
        ge=0.0,
        description="Ratio of overlapping speech duration to total conversation speech duration.",
    )


class AudioAnalysisResult(BaseModel):
    """Composite payload containing the full transcript, chronological timeline, and agent synthesis."""

    overall_transcript: str = Field(
        ..., description="Full consolidated transcript formatted with speaker tags."
    )
    timeline: List[TimelineEvent] = Field(
        ..., description="Chronological list of synchronized timeline events."
    )
    agent_context: Optional[AgentSynthesis] = Field(
        default=None,
        description="High-level synthesis and structured reasoning from the LangGraph agent.",
    )


class AudioResponse(BaseModel):
    """The root response schema returned by the primary analysis endpoint."""

    file_name: str = Field(..., description="Name of the processed audio file.")
    speakers_detected: List[str] = Field(
        ..., description="Unique speaker IDs identified in the session."
    )
    analysis: AudioAnalysisResult = Field(..., description="Complete multi-modal output payload.")
